// Mocks generated by Mockito 5.4.6 from annotations
// in viam_flutter_bluetooth_provisioning_widget/test/mocks/generate_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i16;
import 'dart:typed_data' as _i17;

import 'package:fixnum/fixnum.dart' as _i13;
import 'package:flutter_blue_plus/flutter_blue_plus.dart' as _i3;
import 'package:flutter_blue_plus_platform_interface/flutter_blue_plus_platform_interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;
import 'package:protobuf/protobuf.dart' as _i10;
import 'package:viam_sdk/src/app/app.dart' as _i4;
import 'package:viam_sdk/src/app/billing.dart' as _i6;
import 'package:viam_sdk/src/app/data.dart' as _i7;
import 'package:viam_sdk/src/app/provisioning.dart' as _i8;
import 'package:viam_sdk/src/app/robot.dart' as _i5;
import 'package:viam_sdk/src/gen/app/v1/app.pbgrpc.dart' as _i12;
import 'package:viam_sdk/src/gen/google/protobuf/struct.pb.dart' as _i14;
import 'package:viam_sdk/src/gen/google/protobuf/timestamp.pb.dart' as _i11;
import 'package:viam_sdk/src/robot/client.dart' as _i9;
import 'package:viam_sdk/src/viam_sdk.dart' as _i18;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDeviceIdentifier_0 extends _i1.SmartFake
    implements _i2.DeviceIdentifier {
  _FakeDeviceIdentifier_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGuid_1 extends _i1.SmartFake implements _i2.Guid {
  _FakeGuid_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBluetoothDevice_2 extends _i1.SmartFake
    implements _i3.BluetoothDevice {
  _FakeBluetoothDevice_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCharacteristicProperties_3 extends _i1.SmartFake
    implements _i3.CharacteristicProperties {
  _FakeCharacteristicProperties_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppClient_4 extends _i1.SmartFake implements _i4.AppClient {
  _FakeAppClient_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppRobotClient_5 extends _i1.SmartFake
    implements _i5.AppRobotClient {
  _FakeAppRobotClient_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBillingClient_6 extends _i1.SmartFake implements _i6.BillingClient {
  _FakeBillingClient_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDataClient_7 extends _i1.SmartFake implements _i7.DataClient {
  _FakeDataClient_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProvisioningClient_8 extends _i1.SmartFake
    implements _i8.ProvisioningClient {
  _FakeProvisioningClient_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRobotClient_9 extends _i1.SmartFake implements _i9.RobotClient {
  _FakeRobotClient_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBuilderInfo_10 extends _i1.SmartFake implements _i10.BuilderInfo {
  _FakeBuilderInfo_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTimestamp_11 extends _i1.SmartFake implements _i11.Timestamp {
  _FakeTimestamp_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUnknownFieldSet_12 extends _i1.SmartFake
    implements _i10.UnknownFieldSet {
  _FakeUnknownFieldSet_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRobot_13 extends _i1.SmartFake implements _i12.Robot {
  _FakeRobot_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGeneratedMessage_14 extends _i1.SmartFake
    implements _i10.GeneratedMessage {
  _FakeGeneratedMessage_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInt64_15 extends _i1.SmartFake implements _i13.Int64 {
  _FakeInt64_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStruct_16 extends _i1.SmartFake implements _i14.Struct {
  _FakeStruct_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRobotPart_17 extends _i1.SmartFake implements _i12.RobotPart {
  _FakeRobotPart_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BluetoothDevice].
///
/// See the documentation for Mockito's code generation for more information.
class MockBluetoothDevice extends _i1.Mock implements _i3.BluetoothDevice {
  MockBluetoothDevice() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DeviceIdentifier get remoteId => (super.noSuchMethod(
        Invocation.getter(#remoteId),
        returnValue: _FakeDeviceIdentifier_0(
          this,
          Invocation.getter(#remoteId),
        ),
      ) as _i2.DeviceIdentifier);

  @override
  String get platformName => (super.noSuchMethod(
        Invocation.getter(#platformName),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#platformName),
        ),
      ) as String);

  @override
  String get advName => (super.noSuchMethod(
        Invocation.getter(#advName),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#advName),
        ),
      ) as String);

  @override
  List<_i3.BluetoothService> get servicesList => (super.noSuchMethod(
        Invocation.getter(#servicesList),
        returnValue: <_i3.BluetoothService>[],
      ) as List<_i3.BluetoothService>);

  @override
  bool get isAutoConnectEnabled => (super.noSuchMethod(
        Invocation.getter(#isAutoConnectEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  bool get isDisconnected => (super.noSuchMethod(
        Invocation.getter(#isDisconnected),
        returnValue: false,
      ) as bool);

  @override
  _i16.Stream<_i3.BluetoothConnectionState> get connectionState =>
      (super.noSuchMethod(
        Invocation.getter(#connectionState),
        returnValue: _i16.Stream<_i3.BluetoothConnectionState>.empty(),
      ) as _i16.Stream<_i3.BluetoothConnectionState>);

  @override
  int get mtuNow => (super.noSuchMethod(
        Invocation.getter(#mtuNow),
        returnValue: 0,
      ) as int);

  @override
  _i16.Stream<int> get mtu => (super.noSuchMethod(
        Invocation.getter(#mtu),
        returnValue: _i16.Stream<int>.empty(),
      ) as _i16.Stream<int>);

  @override
  _i16.Stream<void> get onServicesReset => (super.noSuchMethod(
        Invocation.getter(#onServicesReset),
        returnValue: _i16.Stream<void>.empty(),
      ) as _i16.Stream<void>);

  @override
  _i16.Stream<_i3.BluetoothBondState> get bondState => (super.noSuchMethod(
        Invocation.getter(#bondState),
        returnValue: _i16.Stream<_i3.BluetoothBondState>.empty(),
      ) as _i16.Stream<_i3.BluetoothBondState>);

  @override
  _i16.Stream<bool> get isDiscoveringServices => (super.noSuchMethod(
        Invocation.getter(#isDiscoveringServices),
        returnValue: _i16.Stream<bool>.empty(),
      ) as _i16.Stream<bool>);

  @override
  _i2.DeviceIdentifier get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _FakeDeviceIdentifier_0(
          this,
          Invocation.getter(#id),
        ),
      ) as _i2.DeviceIdentifier);

  @override
  String get localName => (super.noSuchMethod(
        Invocation.getter(#localName),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#localName),
        ),
      ) as String);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  _i16.Stream<_i3.BluetoothConnectionState> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i16.Stream<_i3.BluetoothConnectionState>.empty(),
      ) as _i16.Stream<_i3.BluetoothConnectionState>);

  @override
  _i16.Stream<List<_i3.BluetoothService>> get servicesStream =>
      (super.noSuchMethod(
        Invocation.getter(#servicesStream),
        returnValue: _i16.Stream<List<_i3.BluetoothService>>.empty(),
      ) as _i16.Stream<List<_i3.BluetoothService>>);

  @override
  _i16.Stream<List<_i3.BluetoothService>> get services => (super.noSuchMethod(
        Invocation.getter(#services),
        returnValue: _i16.Stream<List<_i3.BluetoothService>>.empty(),
      ) as _i16.Stream<List<_i3.BluetoothService>>);

  @override
  void cancelWhenDisconnected(
    _i16.StreamSubscription<dynamic>? subscription, {
    bool? next = false,
    bool? delayed = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #cancelWhenDisconnected,
          [subscription],
          {
            #next: next,
            #delayed: delayed,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i16.Future<void> connect({
    Duration? timeout = const Duration(seconds: 35),
    int? mtu = 512,
    bool? autoConnect = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
          {
            #timeout: timeout,
            #mtu: mtu,
            #autoConnect: autoConnect,
          },
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> disconnect({
    int? timeout = 35,
    bool? queue = true,
    int? androidDelay = 2000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
          {
            #timeout: timeout,
            #queue: queue,
            #androidDelay: androidDelay,
          },
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<List<_i3.BluetoothService>> discoverServices({
    bool? subscribeToServicesChanged = true,
    int? timeout = 15,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverServices,
          [],
          {
            #subscribeToServicesChanged: subscribeToServicesChanged,
            #timeout: timeout,
          },
        ),
        returnValue: _i16.Future<List<_i3.BluetoothService>>.value(
            <_i3.BluetoothService>[]),
      ) as _i16.Future<List<_i3.BluetoothService>>);

  @override
  _i16.Future<int> readRssi({int? timeout = 15}) => (super.noSuchMethod(
        Invocation.method(
          #readRssi,
          [],
          {#timeout: timeout},
        ),
        returnValue: _i16.Future<int>.value(0),
      ) as _i16.Future<int>);

  @override
  _i16.Future<int> requestMtu(
    int? desiredMtu, {
    double? predelay = 0.35,
    int? timeout = 15,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestMtu,
          [desiredMtu],
          {
            #predelay: predelay,
            #timeout: timeout,
          },
        ),
        returnValue: _i16.Future<int>.value(0),
      ) as _i16.Future<int>);

  @override
  _i16.Future<void> requestConnectionPriority(
          {required _i3.ConnectionPriority? connectionPriorityRequest}) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestConnectionPriority,
          [],
          {#connectionPriorityRequest: connectionPriorityRequest},
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> setPreferredPhy({
    required int? txPhy,
    required int? rxPhy,
    required _i3.PhyCoding? option,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPreferredPhy,
          [],
          {
            #txPhy: txPhy,
            #rxPhy: rxPhy,
            #option: option,
          },
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> createBond({
    int? timeout = 90,
    _i17.Uint8List? pin,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBond,
          [],
          {
            #timeout: timeout,
            #pin: pin,
          },
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> removeBond({int? timeout = 30}) => (super.noSuchMethod(
        Invocation.method(
          #removeBond,
          [],
          {#timeout: timeout},
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> clearGattCache() => (super.noSuchMethod(
        Invocation.method(
          #clearGattCache,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> pair() => (super.noSuchMethod(
        Invocation.method(
          #pair,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
}

/// A class which mocks [BluetoothService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBluetoothService extends _i1.Mock implements _i3.BluetoothService {
  MockBluetoothService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DeviceIdentifier get remoteId => (super.noSuchMethod(
        Invocation.getter(#remoteId),
        returnValue: _FakeDeviceIdentifier_0(
          this,
          Invocation.getter(#remoteId),
        ),
      ) as _i2.DeviceIdentifier);

  @override
  _i2.Guid get serviceUuid => (super.noSuchMethod(
        Invocation.getter(#serviceUuid),
        returnValue: _FakeGuid_1(
          this,
          Invocation.getter(#serviceUuid),
        ),
      ) as _i2.Guid);

  @override
  List<_i3.BluetoothCharacteristic> get characteristics => (super.noSuchMethod(
        Invocation.getter(#characteristics),
        returnValue: <_i3.BluetoothCharacteristic>[],
      ) as List<_i3.BluetoothCharacteristic>);

  @override
  _i2.Guid get uuid => (super.noSuchMethod(
        Invocation.getter(#uuid),
        returnValue: _FakeGuid_1(
          this,
          Invocation.getter(#uuid),
        ),
      ) as _i2.Guid);

  @override
  bool get isPrimary => (super.noSuchMethod(
        Invocation.getter(#isPrimary),
        returnValue: false,
      ) as bool);

  @override
  bool get isSecondary => (super.noSuchMethod(
        Invocation.getter(#isSecondary),
        returnValue: false,
      ) as bool);

  @override
  List<_i3.BluetoothService> get includedServices => (super.noSuchMethod(
        Invocation.getter(#includedServices),
        returnValue: <_i3.BluetoothService>[],
      ) as List<_i3.BluetoothService>);

  @override
  _i2.DeviceIdentifier get deviceId => (super.noSuchMethod(
        Invocation.getter(#deviceId),
        returnValue: _FakeDeviceIdentifier_0(
          this,
          Invocation.getter(#deviceId),
        ),
      ) as _i2.DeviceIdentifier);
}

/// A class which mocks [BluetoothCharacteristic].
///
/// See the documentation for Mockito's code generation for more information.
class MockBluetoothCharacteristic extends _i1.Mock
    implements _i3.BluetoothCharacteristic {
  MockBluetoothCharacteristic() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DeviceIdentifier get remoteId => (super.noSuchMethod(
        Invocation.getter(#remoteId),
        returnValue: _FakeDeviceIdentifier_0(
          this,
          Invocation.getter(#remoteId),
        ),
      ) as _i2.DeviceIdentifier);

  @override
  _i2.Guid get serviceUuid => (super.noSuchMethod(
        Invocation.getter(#serviceUuid),
        returnValue: _FakeGuid_1(
          this,
          Invocation.getter(#serviceUuid),
        ),
      ) as _i2.Guid);

  @override
  _i2.Guid get characteristicUuid => (super.noSuchMethod(
        Invocation.getter(#characteristicUuid),
        returnValue: _FakeGuid_1(
          this,
          Invocation.getter(#characteristicUuid),
        ),
      ) as _i2.Guid);

  @override
  _i2.Guid get uuid => (super.noSuchMethod(
        Invocation.getter(#uuid),
        returnValue: _FakeGuid_1(
          this,
          Invocation.getter(#uuid),
        ),
      ) as _i2.Guid);

  @override
  _i3.BluetoothDevice get device => (super.noSuchMethod(
        Invocation.getter(#device),
        returnValue: _FakeBluetoothDevice_2(
          this,
          Invocation.getter(#device),
        ),
      ) as _i3.BluetoothDevice);

  @override
  _i3.CharacteristicProperties get properties => (super.noSuchMethod(
        Invocation.getter(#properties),
        returnValue: _FakeCharacteristicProperties_3(
          this,
          Invocation.getter(#properties),
        ),
      ) as _i3.CharacteristicProperties);

  @override
  List<_i3.BluetoothDescriptor> get descriptors => (super.noSuchMethod(
        Invocation.getter(#descriptors),
        returnValue: <_i3.BluetoothDescriptor>[],
      ) as List<_i3.BluetoothDescriptor>);

  @override
  List<int> get lastValue => (super.noSuchMethod(
        Invocation.getter(#lastValue),
        returnValue: <int>[],
      ) as List<int>);

  @override
  _i16.Stream<List<int>> get lastValueStream => (super.noSuchMethod(
        Invocation.getter(#lastValueStream),
        returnValue: _i16.Stream<List<int>>.empty(),
      ) as _i16.Stream<List<int>>);

  @override
  _i16.Stream<List<int>> get onValueReceived => (super.noSuchMethod(
        Invocation.getter(#onValueReceived),
        returnValue: _i16.Stream<List<int>>.empty(),
      ) as _i16.Stream<List<int>>);

  @override
  bool get isNotifying => (super.noSuchMethod(
        Invocation.getter(#isNotifying),
        returnValue: false,
      ) as bool);

  @override
  _i2.DeviceIdentifier get deviceId => (super.noSuchMethod(
        Invocation.getter(#deviceId),
        returnValue: _FakeDeviceIdentifier_0(
          this,
          Invocation.getter(#deviceId),
        ),
      ) as _i2.DeviceIdentifier);

  @override
  _i16.Stream<List<int>> get value => (super.noSuchMethod(
        Invocation.getter(#value),
        returnValue: _i16.Stream<List<int>>.empty(),
      ) as _i16.Stream<List<int>>);

  @override
  _i16.Stream<List<int>> get onValueChangedStream => (super.noSuchMethod(
        Invocation.getter(#onValueChangedStream),
        returnValue: _i16.Stream<List<int>>.empty(),
      ) as _i16.Stream<List<int>>);

  @override
  _i16.Future<List<int>> read({int? timeout = 15}) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [],
          {#timeout: timeout},
        ),
        returnValue: _i16.Future<List<int>>.value(<int>[]),
      ) as _i16.Future<List<int>>);

  @override
  _i16.Future<void> write(
    List<int>? value, {
    bool? withoutResponse = false,
    bool? allowLongWrite = false,
    int? timeout = 15,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [value],
          {
            #withoutResponse: withoutResponse,
            #allowLongWrite: allowLongWrite,
            #timeout: timeout,
          },
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<bool> setNotifyValue(
    bool? notify, {
    int? timeout = 15,
    bool? forceIndications = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNotifyValue,
          [notify],
          {
            #timeout: timeout,
            #forceIndications: forceIndications,
          },
        ),
        returnValue: _i16.Future<bool>.value(false),
      ) as _i16.Future<bool>);
}

/// A class which mocks [Viam].
///
/// See the documentation for Mockito's code generation for more information.
class MockViam extends _i1.Mock implements _i18.Viam {
  MockViam() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.AppClient get appClient => (super.noSuchMethod(
        Invocation.getter(#appClient),
        returnValue: _FakeAppClient_4(
          this,
          Invocation.getter(#appClient),
        ),
      ) as _i4.AppClient);

  @override
  _i5.AppRobotClient get appRobotClient => (super.noSuchMethod(
        Invocation.getter(#appRobotClient),
        returnValue: _FakeAppRobotClient_5(
          this,
          Invocation.getter(#appRobotClient),
        ),
      ) as _i5.AppRobotClient);

  @override
  _i6.BillingClient get billingClient => (super.noSuchMethod(
        Invocation.getter(#billingClient),
        returnValue: _FakeBillingClient_6(
          this,
          Invocation.getter(#billingClient),
        ),
      ) as _i6.BillingClient);

  @override
  _i7.DataClient get dataClient => (super.noSuchMethod(
        Invocation.getter(#dataClient),
        returnValue: _FakeDataClient_7(
          this,
          Invocation.getter(#dataClient),
        ),
      ) as _i7.DataClient);

  @override
  _i8.ProvisioningClient get provisioningClient => (super.noSuchMethod(
        Invocation.getter(#provisioningClient),
        returnValue: _FakeProvisioningClient_8(
          this,
          Invocation.getter(#provisioningClient),
        ),
      ) as _i8.ProvisioningClient);

  @override
  _i16.Future<_i9.RobotClient> getRobotClient(_i12.Robot? robot) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotClient,
          [robot],
        ),
        returnValue: _i16.Future<_i9.RobotClient>.value(_FakeRobotClient_9(
          this,
          Invocation.method(
            #getRobotClient,
            [robot],
          ),
        )),
      ) as _i16.Future<_i9.RobotClient>);
}

/// A class which mocks [Robot].
///
/// See the documentation for Mockito's code generation for more information.
class MockRobot extends _i1.Mock implements _i12.Robot {
  MockRobot() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.BuilderInfo get info_ => (super.noSuchMethod(
        Invocation.getter(#info_),
        returnValue: _FakeBuilderInfo_10(
          this,
          Invocation.getter(#info_),
        ),
      ) as _i10.BuilderInfo);

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  String get location => (super.noSuchMethod(
        Invocation.getter(#location),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#location),
        ),
      ) as String);

  @override
  _i11.Timestamp get lastAccess => (super.noSuchMethod(
        Invocation.getter(#lastAccess),
        returnValue: _FakeTimestamp_11(
          this,
          Invocation.getter(#lastAccess),
        ),
      ) as _i11.Timestamp);

  @override
  _i11.Timestamp get createdOn => (super.noSuchMethod(
        Invocation.getter(#createdOn),
        returnValue: _FakeTimestamp_11(
          this,
          Invocation.getter(#createdOn),
        ),
      ) as _i11.Timestamp);

  @override
  set id(String? v) => super.noSuchMethod(
        Invocation.setter(
          #id,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set name(String? v) => super.noSuchMethod(
        Invocation.setter(
          #name,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set location(String? v) => super.noSuchMethod(
        Invocation.setter(
          #location,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set lastAccess(_i11.Timestamp? v) => super.noSuchMethod(
        Invocation.setter(
          #lastAccess,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set createdOn(_i11.Timestamp? v) => super.noSuchMethod(
        Invocation.setter(
          #createdOn,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.UnknownFieldSet get unknownFields => (super.noSuchMethod(
        Invocation.getter(#unknownFields),
        returnValue: _FakeUnknownFieldSet_12(
          this,
          Invocation.getter(#unknownFields),
        ),
      ) as _i10.UnknownFieldSet);

  @override
  bool get isFrozen => (super.noSuchMethod(
        Invocation.getter(#isFrozen),
        returnValue: false,
      ) as bool);

  @override
  _i12.Robot clone() => (super.noSuchMethod(
        Invocation.method(
          #clone,
          [],
        ),
        returnValue: _FakeRobot_13(
          this,
          Invocation.method(
            #clone,
            [],
          ),
        ),
      ) as _i12.Robot);

  @override
  _i12.Robot copyWith(void Function(_i12.Robot)? updates) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [updates],
        ),
        returnValue: _FakeRobot_13(
          this,
          Invocation.method(
            #copyWith,
            [updates],
          ),
        ),
      ) as _i12.Robot);

  @override
  _i12.Robot createEmptyInstance() => (super.noSuchMethod(
        Invocation.method(
          #createEmptyInstance,
          [],
        ),
        returnValue: _FakeRobot_13(
          this,
          Invocation.method(
            #createEmptyInstance,
            [],
          ),
        ),
      ) as _i12.Robot);

  @override
  bool hasId() => (super.noSuchMethod(
        Invocation.method(
          #hasId,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearId() => super.noSuchMethod(
        Invocation.method(
          #clearId,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool hasName() => (super.noSuchMethod(
        Invocation.method(
          #hasName,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearName() => super.noSuchMethod(
        Invocation.method(
          #clearName,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool hasLocation() => (super.noSuchMethod(
        Invocation.method(
          #hasLocation,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearLocation() => super.noSuchMethod(
        Invocation.method(
          #clearLocation,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool hasLastAccess() => (super.noSuchMethod(
        Invocation.method(
          #hasLastAccess,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearLastAccess() => super.noSuchMethod(
        Invocation.method(
          #clearLastAccess,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Timestamp ensureLastAccess() => (super.noSuchMethod(
        Invocation.method(
          #ensureLastAccess,
          [],
        ),
        returnValue: _FakeTimestamp_11(
          this,
          Invocation.method(
            #ensureLastAccess,
            [],
          ),
        ),
      ) as _i11.Timestamp);

  @override
  bool hasCreatedOn() => (super.noSuchMethod(
        Invocation.method(
          #hasCreatedOn,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearCreatedOn() => super.noSuchMethod(
        Invocation.method(
          #clearCreatedOn,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Timestamp ensureCreatedOn() => (super.noSuchMethod(
        Invocation.method(
          #ensureCreatedOn,
          [],
        ),
        returnValue: _FakeTimestamp_11(
          this,
          Invocation.method(
            #ensureCreatedOn,
            [],
          ),
        ),
      ) as _i11.Timestamp);

  @override
  _i10.GeneratedMessage freeze() => (super.noSuchMethod(
        Invocation.method(
          #freeze,
          [],
        ),
        returnValue: _FakeGeneratedMessage_14(
          this,
          Invocation.method(
            #freeze,
            [],
          ),
        ),
      ) as _i10.GeneratedMessage);

  @override
  _i10.GeneratedMessage toBuilder() => (super.noSuchMethod(
        Invocation.method(
          #toBuilder,
          [],
        ),
        returnValue: _FakeGeneratedMessage_14(
          this,
          Invocation.method(
            #toBuilder,
            [],
          ),
        ),
      ) as _i10.GeneratedMessage);

  @override
  bool hasRequiredFields() => (super.noSuchMethod(
        Invocation.method(
          #hasRequiredFields,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isInitialized() => (super.noSuchMethod(
        Invocation.method(
          #isInitialized,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int? getTagNumber(String? fieldName) => (super.noSuchMethod(Invocation.method(
        #getTagNumber,
        [fieldName],
      )) as int?);

  @override
  String toDebugString() => (super.noSuchMethod(
        Invocation.method(
          #toDebugString,
          [],
        ),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.method(
            #toDebugString,
            [],
          ),
        ),
      ) as String);

  @override
  void check() => super.noSuchMethod(
        Invocation.method(
          #check,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i17.Uint8List writeToBuffer() => (super.noSuchMethod(
        Invocation.method(
          #writeToBuffer,
          [],
        ),
        returnValue: _i17.Uint8List(0),
      ) as _i17.Uint8List);

  @override
  void writeToCodedBufferWriter(_i10.CodedBufferWriter? output) =>
      super.noSuchMethod(
        Invocation.method(
          #writeToCodedBufferWriter,
          [output],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void mergeFromCodedBufferReader(
    _i10.CodedBufferReader? input, [
    _i10.ExtensionRegistry? extensionRegistry = _i10.ExtensionRegistry.EMPTY,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #mergeFromCodedBufferReader,
          [
            input,
            extensionRegistry,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void mergeFromBuffer(
    List<int>? input, [
    _i10.ExtensionRegistry? extensionRegistry = _i10.ExtensionRegistry.EMPTY,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #mergeFromBuffer,
          [
            input,
            extensionRegistry,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> writeToJsonMap() => (super.noSuchMethod(
        Invocation.method(
          #writeToJsonMap,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  String writeToJson() => (super.noSuchMethod(
        Invocation.method(
          #writeToJson,
          [],
        ),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.method(
            #writeToJson,
            [],
          ),
        ),
      ) as String);

  @override
  Object? toProto3Json(
          {_i10.TypeRegistry? typeRegistry =
              const _i10.TypeRegistry.empty()}) =>
      (super.noSuchMethod(Invocation.method(
        #toProto3Json,
        [],
        {#typeRegistry: typeRegistry},
      )) as Object?);

  @override
  void mergeFromProto3Json(
    Object? json, {
    _i10.TypeRegistry? typeRegistry = const _i10.TypeRegistry.empty(),
    bool? ignoreUnknownFields = false,
    bool? supportNamesWithUnderscores = true,
    bool? permissiveEnums = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #mergeFromProto3Json,
          [json],
          {
            #typeRegistry: typeRegistry,
            #ignoreUnknownFields: ignoreUnknownFields,
            #supportNamesWithUnderscores: supportNamesWithUnderscores,
            #permissiveEnums: permissiveEnums,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void mergeFromJson(
    String? data, [
    _i10.ExtensionRegistry? extensionRegistry = _i10.ExtensionRegistry.EMPTY,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #mergeFromJson,
          [
            data,
            extensionRegistry,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void mergeFromJsonMap(
    Map<String, dynamic>? json, [
    _i10.ExtensionRegistry? extensionRegistry = _i10.ExtensionRegistry.EMPTY,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #mergeFromJsonMap,
          [
            json,
            extensionRegistry,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addExtension(
    _i10.Extension<dynamic>? extension,
    Object? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #addExtension,
          [
            extension,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearExtension(_i10.Extension<dynamic>? extension) => super.noSuchMethod(
        Invocation.method(
          #clearExtension,
          [extension],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearField(int? tagNumber) => super.noSuchMethod(
        Invocation.method(
          #clearField,
          [tagNumber],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int $_whichOneof(int? oneofIndex) => (super.noSuchMethod(
        Invocation.method(
          #$_whichOneof,
          [oneofIndex],
        ),
        returnValue: 0,
      ) as int);

  @override
  bool extensionsAreInitialized() => (super.noSuchMethod(
        Invocation.method(
          #extensionsAreInitialized,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  dynamic getExtension(_i10.Extension<dynamic>? extension) =>
      super.noSuchMethod(Invocation.method(
        #getExtension,
        [extension],
      ));

  @override
  dynamic getField(int? tagNumber) => super.noSuchMethod(Invocation.method(
        #getField,
        [tagNumber],
      ));

  @override
  List<T> createRepeatedField<T>(
    int? tagNumber,
    _i10.FieldInfo<T>? fi,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRepeatedField,
          [
            tagNumber,
            fi,
          ],
        ),
        returnValue: <T>[],
      ) as List<T>);

  @override
  Map<K, V> createMapField<K, V>(
    int? tagNumber,
    _i10.MapFieldInfo<K, V>? fi,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMapField,
          [
            tagNumber,
            fi,
          ],
        ),
        returnValue: <K, V>{},
      ) as Map<K, V>);

  @override
  dynamic getFieldOrNull(int? tagNumber) =>
      super.noSuchMethod(Invocation.method(
        #getFieldOrNull,
        [tagNumber],
      ));

  @override
  dynamic getDefaultForField(int? tagNumber) =>
      super.noSuchMethod(Invocation.method(
        #getDefaultForField,
        [tagNumber],
      ));

  @override
  bool hasExtension(_i10.Extension<dynamic>? extension) => (super.noSuchMethod(
        Invocation.method(
          #hasExtension,
          [extension],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool hasField(int? tagNumber) => (super.noSuchMethod(
        Invocation.method(
          #hasField,
          [tagNumber],
        ),
        returnValue: false,
      ) as bool);

  @override
  void mergeFromMessage(_i10.GeneratedMessage? other) => super.noSuchMethod(
        Invocation.method(
          #mergeFromMessage,
          [other],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void mergeUnknownFields(_i10.UnknownFieldSet? unknownFieldSet) =>
      super.noSuchMethod(
        Invocation.method(
          #mergeUnknownFields,
          [unknownFieldSet],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setExtension(
    _i10.Extension<dynamic>? extension,
    Object? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setExtension,
          [
            extension,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setField(
    int? tagNumber,
    Object? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setField,
          [
            tagNumber,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  T $_get<T>(
    int? index,
    T? defaultValue,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$_get,
          [
            index,
            defaultValue,
          ],
        ),
        returnValue: _i15.dummyValue<T>(
          this,
          Invocation.method(
            #$_get,
            [
              index,
              defaultValue,
            ],
          ),
        ),
      ) as T);

  @override
  T $_getN<T>(int? index) => (super.noSuchMethod(
        Invocation.method(
          #$_getN,
          [index],
        ),
        returnValue: _i15.dummyValue<T>(
          this,
          Invocation.method(
            #$_getN,
            [index],
          ),
        ),
      ) as T);

  @override
  T $_ensure<T>(int? index) => (super.noSuchMethod(
        Invocation.method(
          #$_ensure,
          [index],
        ),
        returnValue: _i15.dummyValue<T>(
          this,
          Invocation.method(
            #$_ensure,
            [index],
          ),
        ),
      ) as T);

  @override
  List<T> $_getList<T>(int? index) => (super.noSuchMethod(
        Invocation.method(
          #$_getList,
          [index],
        ),
        returnValue: <T>[],
      ) as List<T>);

  @override
  Map<K, V> $_getMap<K, V>(int? index) => (super.noSuchMethod(
        Invocation.method(
          #$_getMap,
          [index],
        ),
        returnValue: <K, V>{},
      ) as Map<K, V>);

  @override
  bool $_getB(
    int? index,
    bool? defaultValue,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$_getB,
          [
            index,
            defaultValue,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool $_getBF(int? index) => (super.noSuchMethod(
        Invocation.method(
          #$_getBF,
          [index],
        ),
        returnValue: false,
      ) as bool);

  @override
  int $_getI(
    int? index,
    int? defaultValue,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$_getI,
          [
            index,
            defaultValue,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  int $_getIZ(int? index) => (super.noSuchMethod(
        Invocation.method(
          #$_getIZ,
          [index],
        ),
        returnValue: 0,
      ) as int);

  @override
  String $_getS(
    int? index,
    String? defaultValue,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$_getS,
          [
            index,
            defaultValue,
          ],
        ),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.method(
            #$_getS,
            [
              index,
              defaultValue,
            ],
          ),
        ),
      ) as String);

  @override
  String $_getSZ(int? index) => (super.noSuchMethod(
        Invocation.method(
          #$_getSZ,
          [index],
        ),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.method(
            #$_getSZ,
            [index],
          ),
        ),
      ) as String);

  @override
  _i13.Int64 $_getI64(int? index) => (super.noSuchMethod(
        Invocation.method(
          #$_getI64,
          [index],
        ),
        returnValue: _FakeInt64_15(
          this,
          Invocation.method(
            #$_getI64,
            [index],
          ),
        ),
      ) as _i13.Int64);

  @override
  bool $_has(int? index) => (super.noSuchMethod(
        Invocation.method(
          #$_has,
          [index],
        ),
        returnValue: false,
      ) as bool);

  @override
  void $_setBool(
    int? index,
    bool? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #$_setBool,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $_setBytes(
    int? index,
    List<int>? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #$_setBytes,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $_setString(
    int? index,
    String? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #$_setString,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $_setFloat(
    int? index,
    double? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #$_setFloat,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $_setDouble(
    int? index,
    double? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #$_setDouble,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $_setSignedInt32(
    int? index,
    int? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #$_setSignedInt32,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $_setUnsignedInt32(
    int? index,
    int? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #$_setUnsignedInt32,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $_setInt64(
    int? index,
    _i13.Int64? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #$_setInt64,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RobotPart].
///
/// See the documentation for Mockito's code generation for more information.
class MockRobotPart extends _i1.Mock implements _i12.RobotPart {
  MockRobotPart() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.BuilderInfo get info_ => (super.noSuchMethod(
        Invocation.getter(#info_),
        returnValue: _FakeBuilderInfo_10(
          this,
          Invocation.getter(#info_),
        ),
      ) as _i10.BuilderInfo);

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  String get secret => (super.noSuchMethod(
        Invocation.getter(#secret),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#secret),
        ),
      ) as String);

  @override
  String get robot => (super.noSuchMethod(
        Invocation.getter(#robot),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#robot),
        ),
      ) as String);

  @override
  _i14.Struct get robotConfig => (super.noSuchMethod(
        Invocation.getter(#robotConfig),
        returnValue: _FakeStruct_16(
          this,
          Invocation.getter(#robotConfig),
        ),
      ) as _i14.Struct);

  @override
  _i11.Timestamp get lastAccess => (super.noSuchMethod(
        Invocation.getter(#lastAccess),
        returnValue: _FakeTimestamp_11(
          this,
          Invocation.getter(#lastAccess),
        ),
      ) as _i11.Timestamp);

  @override
  _i14.Struct get userSuppliedInfo => (super.noSuchMethod(
        Invocation.getter(#userSuppliedInfo),
        returnValue: _FakeStruct_16(
          this,
          Invocation.getter(#userSuppliedInfo),
        ),
      ) as _i14.Struct);

  @override
  bool get mainPart => (super.noSuchMethod(
        Invocation.getter(#mainPart),
        returnValue: false,
      ) as bool);

  @override
  String get fqdn => (super.noSuchMethod(
        Invocation.getter(#fqdn),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#fqdn),
        ),
      ) as String);

  @override
  String get dnsName => (super.noSuchMethod(
        Invocation.getter(#dnsName),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#dnsName),
        ),
      ) as String);

  @override
  String get localFqdn => (super.noSuchMethod(
        Invocation.getter(#localFqdn),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#localFqdn),
        ),
      ) as String);

  @override
  String get locationId => (super.noSuchMethod(
        Invocation.getter(#locationId),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#locationId),
        ),
      ) as String);

  @override
  _i11.Timestamp get createdOn => (super.noSuchMethod(
        Invocation.getter(#createdOn),
        returnValue: _FakeTimestamp_11(
          this,
          Invocation.getter(#createdOn),
        ),
      ) as _i11.Timestamp);

  @override
  List<_i12.SharedSecret> get secrets => (super.noSuchMethod(
        Invocation.getter(#secrets),
        returnValue: <_i12.SharedSecret>[],
      ) as List<_i12.SharedSecret>);

  @override
  _i11.Timestamp get lastUpdated => (super.noSuchMethod(
        Invocation.getter(#lastUpdated),
        returnValue: _FakeTimestamp_11(
          this,
          Invocation.getter(#lastUpdated),
        ),
      ) as _i11.Timestamp);

  @override
  set id(String? v) => super.noSuchMethod(
        Invocation.setter(
          #id,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set name(String? v) => super.noSuchMethod(
        Invocation.setter(
          #name,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set secret(String? v) => super.noSuchMethod(
        Invocation.setter(
          #secret,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set robot(String? v) => super.noSuchMethod(
        Invocation.setter(
          #robot,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set robotConfig(_i14.Struct? v) => super.noSuchMethod(
        Invocation.setter(
          #robotConfig,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set lastAccess(_i11.Timestamp? v) => super.noSuchMethod(
        Invocation.setter(
          #lastAccess,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set userSuppliedInfo(_i14.Struct? v) => super.noSuchMethod(
        Invocation.setter(
          #userSuppliedInfo,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set mainPart(bool? v) => super.noSuchMethod(
        Invocation.setter(
          #mainPart,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set fqdn(String? v) => super.noSuchMethod(
        Invocation.setter(
          #fqdn,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set dnsName(String? v) => super.noSuchMethod(
        Invocation.setter(
          #dnsName,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set localFqdn(String? v) => super.noSuchMethod(
        Invocation.setter(
          #localFqdn,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set locationId(String? v) => super.noSuchMethod(
        Invocation.setter(
          #locationId,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set createdOn(_i11.Timestamp? v) => super.noSuchMethod(
        Invocation.setter(
          #createdOn,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set lastUpdated(_i11.Timestamp? v) => super.noSuchMethod(
        Invocation.setter(
          #lastUpdated,
          v,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.UnknownFieldSet get unknownFields => (super.noSuchMethod(
        Invocation.getter(#unknownFields),
        returnValue: _FakeUnknownFieldSet_12(
          this,
          Invocation.getter(#unknownFields),
        ),
      ) as _i10.UnknownFieldSet);

  @override
  bool get isFrozen => (super.noSuchMethod(
        Invocation.getter(#isFrozen),
        returnValue: false,
      ) as bool);

  @override
  _i12.RobotPart clone() => (super.noSuchMethod(
        Invocation.method(
          #clone,
          [],
        ),
        returnValue: _FakeRobotPart_17(
          this,
          Invocation.method(
            #clone,
            [],
          ),
        ),
      ) as _i12.RobotPart);

  @override
  _i12.RobotPart copyWith(void Function(_i12.RobotPart)? updates) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [updates],
        ),
        returnValue: _FakeRobotPart_17(
          this,
          Invocation.method(
            #copyWith,
            [updates],
          ),
        ),
      ) as _i12.RobotPart);

  @override
  _i12.RobotPart createEmptyInstance() => (super.noSuchMethod(
        Invocation.method(
          #createEmptyInstance,
          [],
        ),
        returnValue: _FakeRobotPart_17(
          this,
          Invocation.method(
            #createEmptyInstance,
            [],
          ),
        ),
      ) as _i12.RobotPart);

  @override
  bool hasId() => (super.noSuchMethod(
        Invocation.method(
          #hasId,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearId() => super.noSuchMethod(
        Invocation.method(
          #clearId,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool hasName() => (super.noSuchMethod(
        Invocation.method(
          #hasName,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearName() => super.noSuchMethod(
        Invocation.method(
          #clearName,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool hasSecret() => (super.noSuchMethod(
        Invocation.method(
          #hasSecret,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearSecret() => super.noSuchMethod(
        Invocation.method(
          #clearSecret,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool hasRobot() => (super.noSuchMethod(
        Invocation.method(
          #hasRobot,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearRobot() => super.noSuchMethod(
        Invocation.method(
          #clearRobot,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool hasRobotConfig() => (super.noSuchMethod(
        Invocation.method(
          #hasRobotConfig,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearRobotConfig() => super.noSuchMethod(
        Invocation.method(
          #clearRobotConfig,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.Struct ensureRobotConfig() => (super.noSuchMethod(
        Invocation.method(
          #ensureRobotConfig,
          [],
        ),
        returnValue: _FakeStruct_16(
          this,
          Invocation.method(
            #ensureRobotConfig,
            [],
          ),
        ),
      ) as _i14.Struct);

  @override
  bool hasLastAccess() => (super.noSuchMethod(
        Invocation.method(
          #hasLastAccess,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearLastAccess() => super.noSuchMethod(
        Invocation.method(
          #clearLastAccess,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Timestamp ensureLastAccess() => (super.noSuchMethod(
        Invocation.method(
          #ensureLastAccess,
          [],
        ),
        returnValue: _FakeTimestamp_11(
          this,
          Invocation.method(
            #ensureLastAccess,
            [],
          ),
        ),
      ) as _i11.Timestamp);

  @override
  bool hasUserSuppliedInfo() => (super.noSuchMethod(
        Invocation.method(
          #hasUserSuppliedInfo,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearUserSuppliedInfo() => super.noSuchMethod(
        Invocation.method(
          #clearUserSuppliedInfo,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.Struct ensureUserSuppliedInfo() => (super.noSuchMethod(
        Invocation.method(
          #ensureUserSuppliedInfo,
          [],
        ),
        returnValue: _FakeStruct_16(
          this,
          Invocation.method(
            #ensureUserSuppliedInfo,
            [],
          ),
        ),
      ) as _i14.Struct);

  @override
  bool hasMainPart() => (super.noSuchMethod(
        Invocation.method(
          #hasMainPart,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearMainPart() => super.noSuchMethod(
        Invocation.method(
          #clearMainPart,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool hasFqdn() => (super.noSuchMethod(
        Invocation.method(
          #hasFqdn,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearFqdn() => super.noSuchMethod(
        Invocation.method(
          #clearFqdn,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool hasDnsName() => (super.noSuchMethod(
        Invocation.method(
          #hasDnsName,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearDnsName() => super.noSuchMethod(
        Invocation.method(
          #clearDnsName,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool hasLocalFqdn() => (super.noSuchMethod(
        Invocation.method(
          #hasLocalFqdn,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearLocalFqdn() => super.noSuchMethod(
        Invocation.method(
          #clearLocalFqdn,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool hasLocationId() => (super.noSuchMethod(
        Invocation.method(
          #hasLocationId,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearLocationId() => super.noSuchMethod(
        Invocation.method(
          #clearLocationId,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool hasCreatedOn() => (super.noSuchMethod(
        Invocation.method(
          #hasCreatedOn,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearCreatedOn() => super.noSuchMethod(
        Invocation.method(
          #clearCreatedOn,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Timestamp ensureCreatedOn() => (super.noSuchMethod(
        Invocation.method(
          #ensureCreatedOn,
          [],
        ),
        returnValue: _FakeTimestamp_11(
          this,
          Invocation.method(
            #ensureCreatedOn,
            [],
          ),
        ),
      ) as _i11.Timestamp);

  @override
  bool hasLastUpdated() => (super.noSuchMethod(
        Invocation.method(
          #hasLastUpdated,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearLastUpdated() => super.noSuchMethod(
        Invocation.method(
          #clearLastUpdated,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Timestamp ensureLastUpdated() => (super.noSuchMethod(
        Invocation.method(
          #ensureLastUpdated,
          [],
        ),
        returnValue: _FakeTimestamp_11(
          this,
          Invocation.method(
            #ensureLastUpdated,
            [],
          ),
        ),
      ) as _i11.Timestamp);

  @override
  _i10.GeneratedMessage freeze() => (super.noSuchMethod(
        Invocation.method(
          #freeze,
          [],
        ),
        returnValue: _FakeGeneratedMessage_14(
          this,
          Invocation.method(
            #freeze,
            [],
          ),
        ),
      ) as _i10.GeneratedMessage);

  @override
  _i10.GeneratedMessage toBuilder() => (super.noSuchMethod(
        Invocation.method(
          #toBuilder,
          [],
        ),
        returnValue: _FakeGeneratedMessage_14(
          this,
          Invocation.method(
            #toBuilder,
            [],
          ),
        ),
      ) as _i10.GeneratedMessage);

  @override
  bool hasRequiredFields() => (super.noSuchMethod(
        Invocation.method(
          #hasRequiredFields,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isInitialized() => (super.noSuchMethod(
        Invocation.method(
          #isInitialized,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int? getTagNumber(String? fieldName) => (super.noSuchMethod(Invocation.method(
        #getTagNumber,
        [fieldName],
      )) as int?);

  @override
  String toDebugString() => (super.noSuchMethod(
        Invocation.method(
          #toDebugString,
          [],
        ),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.method(
            #toDebugString,
            [],
          ),
        ),
      ) as String);

  @override
  void check() => super.noSuchMethod(
        Invocation.method(
          #check,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i17.Uint8List writeToBuffer() => (super.noSuchMethod(
        Invocation.method(
          #writeToBuffer,
          [],
        ),
        returnValue: _i17.Uint8List(0),
      ) as _i17.Uint8List);

  @override
  void writeToCodedBufferWriter(_i10.CodedBufferWriter? output) =>
      super.noSuchMethod(
        Invocation.method(
          #writeToCodedBufferWriter,
          [output],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void mergeFromCodedBufferReader(
    _i10.CodedBufferReader? input, [
    _i10.ExtensionRegistry? extensionRegistry = _i10.ExtensionRegistry.EMPTY,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #mergeFromCodedBufferReader,
          [
            input,
            extensionRegistry,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void mergeFromBuffer(
    List<int>? input, [
    _i10.ExtensionRegistry? extensionRegistry = _i10.ExtensionRegistry.EMPTY,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #mergeFromBuffer,
          [
            input,
            extensionRegistry,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> writeToJsonMap() => (super.noSuchMethod(
        Invocation.method(
          #writeToJsonMap,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  String writeToJson() => (super.noSuchMethod(
        Invocation.method(
          #writeToJson,
          [],
        ),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.method(
            #writeToJson,
            [],
          ),
        ),
      ) as String);

  @override
  Object? toProto3Json(
          {_i10.TypeRegistry? typeRegistry =
              const _i10.TypeRegistry.empty()}) =>
      (super.noSuchMethod(Invocation.method(
        #toProto3Json,
        [],
        {#typeRegistry: typeRegistry},
      )) as Object?);

  @override
  void mergeFromProto3Json(
    Object? json, {
    _i10.TypeRegistry? typeRegistry = const _i10.TypeRegistry.empty(),
    bool? ignoreUnknownFields = false,
    bool? supportNamesWithUnderscores = true,
    bool? permissiveEnums = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #mergeFromProto3Json,
          [json],
          {
            #typeRegistry: typeRegistry,
            #ignoreUnknownFields: ignoreUnknownFields,
            #supportNamesWithUnderscores: supportNamesWithUnderscores,
            #permissiveEnums: permissiveEnums,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void mergeFromJson(
    String? data, [
    _i10.ExtensionRegistry? extensionRegistry = _i10.ExtensionRegistry.EMPTY,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #mergeFromJson,
          [
            data,
            extensionRegistry,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void mergeFromJsonMap(
    Map<String, dynamic>? json, [
    _i10.ExtensionRegistry? extensionRegistry = _i10.ExtensionRegistry.EMPTY,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #mergeFromJsonMap,
          [
            json,
            extensionRegistry,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addExtension(
    _i10.Extension<dynamic>? extension,
    Object? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #addExtension,
          [
            extension,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearExtension(_i10.Extension<dynamic>? extension) => super.noSuchMethod(
        Invocation.method(
          #clearExtension,
          [extension],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearField(int? tagNumber) => super.noSuchMethod(
        Invocation.method(
          #clearField,
          [tagNumber],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int $_whichOneof(int? oneofIndex) => (super.noSuchMethod(
        Invocation.method(
          #$_whichOneof,
          [oneofIndex],
        ),
        returnValue: 0,
      ) as int);

  @override
  bool extensionsAreInitialized() => (super.noSuchMethod(
        Invocation.method(
          #extensionsAreInitialized,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  dynamic getExtension(_i10.Extension<dynamic>? extension) =>
      super.noSuchMethod(Invocation.method(
        #getExtension,
        [extension],
      ));

  @override
  dynamic getField(int? tagNumber) => super.noSuchMethod(Invocation.method(
        #getField,
        [tagNumber],
      ));

  @override
  List<T> createRepeatedField<T>(
    int? tagNumber,
    _i10.FieldInfo<T>? fi,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRepeatedField,
          [
            tagNumber,
            fi,
          ],
        ),
        returnValue: <T>[],
      ) as List<T>);

  @override
  Map<K, V> createMapField<K, V>(
    int? tagNumber,
    _i10.MapFieldInfo<K, V>? fi,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMapField,
          [
            tagNumber,
            fi,
          ],
        ),
        returnValue: <K, V>{},
      ) as Map<K, V>);

  @override
  dynamic getFieldOrNull(int? tagNumber) =>
      super.noSuchMethod(Invocation.method(
        #getFieldOrNull,
        [tagNumber],
      ));

  @override
  dynamic getDefaultForField(int? tagNumber) =>
      super.noSuchMethod(Invocation.method(
        #getDefaultForField,
        [tagNumber],
      ));

  @override
  bool hasExtension(_i10.Extension<dynamic>? extension) => (super.noSuchMethod(
        Invocation.method(
          #hasExtension,
          [extension],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool hasField(int? tagNumber) => (super.noSuchMethod(
        Invocation.method(
          #hasField,
          [tagNumber],
        ),
        returnValue: false,
      ) as bool);

  @override
  void mergeFromMessage(_i10.GeneratedMessage? other) => super.noSuchMethod(
        Invocation.method(
          #mergeFromMessage,
          [other],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void mergeUnknownFields(_i10.UnknownFieldSet? unknownFieldSet) =>
      super.noSuchMethod(
        Invocation.method(
          #mergeUnknownFields,
          [unknownFieldSet],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setExtension(
    _i10.Extension<dynamic>? extension,
    Object? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setExtension,
          [
            extension,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setField(
    int? tagNumber,
    Object? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setField,
          [
            tagNumber,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  T $_get<T>(
    int? index,
    T? defaultValue,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$_get,
          [
            index,
            defaultValue,
          ],
        ),
        returnValue: _i15.dummyValue<T>(
          this,
          Invocation.method(
            #$_get,
            [
              index,
              defaultValue,
            ],
          ),
        ),
      ) as T);

  @override
  T $_getN<T>(int? index) => (super.noSuchMethod(
        Invocation.method(
          #$_getN,
          [index],
        ),
        returnValue: _i15.dummyValue<T>(
          this,
          Invocation.method(
            #$_getN,
            [index],
          ),
        ),
      ) as T);

  @override
  T $_ensure<T>(int? index) => (super.noSuchMethod(
        Invocation.method(
          #$_ensure,
          [index],
        ),
        returnValue: _i15.dummyValue<T>(
          this,
          Invocation.method(
            #$_ensure,
            [index],
          ),
        ),
      ) as T);

  @override
  List<T> $_getList<T>(int? index) => (super.noSuchMethod(
        Invocation.method(
          #$_getList,
          [index],
        ),
        returnValue: <T>[],
      ) as List<T>);

  @override
  Map<K, V> $_getMap<K, V>(int? index) => (super.noSuchMethod(
        Invocation.method(
          #$_getMap,
          [index],
        ),
        returnValue: <K, V>{},
      ) as Map<K, V>);

  @override
  bool $_getB(
    int? index,
    bool? defaultValue,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$_getB,
          [
            index,
            defaultValue,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool $_getBF(int? index) => (super.noSuchMethod(
        Invocation.method(
          #$_getBF,
          [index],
        ),
        returnValue: false,
      ) as bool);

  @override
  int $_getI(
    int? index,
    int? defaultValue,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$_getI,
          [
            index,
            defaultValue,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  int $_getIZ(int? index) => (super.noSuchMethod(
        Invocation.method(
          #$_getIZ,
          [index],
        ),
        returnValue: 0,
      ) as int);

  @override
  String $_getS(
    int? index,
    String? defaultValue,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$_getS,
          [
            index,
            defaultValue,
          ],
        ),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.method(
            #$_getS,
            [
              index,
              defaultValue,
            ],
          ),
        ),
      ) as String);

  @override
  String $_getSZ(int? index) => (super.noSuchMethod(
        Invocation.method(
          #$_getSZ,
          [index],
        ),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.method(
            #$_getSZ,
            [index],
          ),
        ),
      ) as String);

  @override
  _i13.Int64 $_getI64(int? index) => (super.noSuchMethod(
        Invocation.method(
          #$_getI64,
          [index],
        ),
        returnValue: _FakeInt64_15(
          this,
          Invocation.method(
            #$_getI64,
            [index],
          ),
        ),
      ) as _i13.Int64);

  @override
  bool $_has(int? index) => (super.noSuchMethod(
        Invocation.method(
          #$_has,
          [index],
        ),
        returnValue: false,
      ) as bool);

  @override
  void $_setBool(
    int? index,
    bool? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #$_setBool,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $_setBytes(
    int? index,
    List<int>? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #$_setBytes,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $_setString(
    int? index,
    String? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #$_setString,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $_setFloat(
    int? index,
    double? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #$_setFloat,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $_setDouble(
    int? index,
    double? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #$_setDouble,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $_setSignedInt32(
    int? index,
    int? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #$_setSignedInt32,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $_setUnsignedInt32(
    int? index,
    int? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #$_setUnsignedInt32,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $_setInt64(
    int? index,
    _i13.Int64? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #$_setInt64,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
